name: ems_superquadric
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.2
  - numpy=2.2.6
  - scipy=1.15.3
  - numba=0.61.2
  - matplotlib=3.10.3
  - scikit-learn=1.7.0
  - vtk=9.4.2
  - pip
  - pip:
      - plyfile==1.1.2
      - open3d==0.17.0
      - tqdm==4.67.1
      - pyyaml==6.0.2
      - joblib==1.5.1
      - threadpoolctl==3.6.0
